[build]
  command = "npm run build && npm run postbuild"
  publish = "dist"

# Redirect API requests to the server
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# For all other routes, serve the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"